name: Eclipse ESCET BVS Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/experiment-eclipse-escet.yml"

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://gitlab.eclipse.org/ribafish/eclipse-escet.git"
  BRANCH: "feature/dv2.0_tycho-caching"
  ARGS: "-Dscan.tag.gk-eclipse-exp"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        goals:
          - "install -DskipTests=true -Dscan.tag.skipTests"
          - "install"
          - "verify"
        experimentId: [1, 2]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Xvfb and run experiment 1
        if: matrix.experimentId == 1
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: bash
        run: |
          cd develocity-maven-build-validation
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./01-validate-local-build-caching-same-location.sh -r ${{ env.GIT_REPO }} -g "${{ matrix.goals }}" -a "${{ env.ARGS }}" -s ${{ env.DEVELOCITY_URL }} -b ${{ env.BRANCH }}
      - name: Set up Xvfb and run experiment 2
        if: matrix.experimentId == 2
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
        shell: bash
        run: |
          cd develocity-maven-build-validation
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./02-validate-local-build-caching-different-locations.sh -r ${{ env.GIT_REPO }} -g "${{ matrix.goals }}" -a "${{ env.ARGS }}" -s ${{ env.DEVELOCITY_URL }} -b ${{ env.BRANCH }}
#      - name: Run experiment 1
#        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-1@actions-stable
#        if: matrix.experimentId == 1
#        env:
#          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        with:
#          gitRepo: ${{ env.GIT_REPO }}
#          goals: ${{ matrix.goals }}
#          args: ${{ env.ARGS }}
#          develocityUrl: ${{ env.DEVELOCITY_URL }}
#          failIfNotFullyCacheable: false
#          gitBranch: ${{ env.BRANCH }}
#      - name: Run experiment 2
#        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-2@actions-stable
#        if: matrix.experimentId == 2
#        env:
#          DEVELOCITY_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
#        with:
#          gitRepo: ${{ env.GIT_REPO }}
#          goals: ${{ matrix.goals }}
#          args: ${{ env.ARGS }}
#          develocityUrl: ${{ env.DEVELOCITY_URL }}
#          failIfNotFullyCacheable: false
#          gitBranch: ${{ env.BRANCH }}