name: DuckDuckGo Android Browser BVS Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/experiment-duckdcukgo.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/ribafish/duckduckgo-Android.git"
  BRANCH: "gk/develocity"
  ARGS: ""
  GIT_ARGS: "--recursive"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        tasks:
          - "assembleInternalDebug"
          - "code_format_checks"
          - "jvm_tests"
          - "lint"
          - "androidTestsBuild"
          - "test"
        experimentId: [1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18.3'
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-1@actions-stable
        if: matrix.experimentId == 1
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ matrix.tasks }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
          gitBranch: ${{ env.BRANCH }}
          gitOptions: ${{ env.GIT_ARGS }}
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-2@actions-stable
        if: matrix.experimentId == 2
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ matrix.tasks }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
          gitBranch: ${{ env.BRANCH }}
          gitOptions: ${{ env.GIT_ARGS }}
      - name: Run experiment 3
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        if: matrix.experimentId == 3
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ matrix.tasks }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
          gitBranch: ${{ env.BRANCH }}
          gitOptions: ${{ env.GIT_ARGS }}
